### What is numpy?

* 1. NumPy (Numerical Python) is an open source Python library.
* 2. The NumPy library contains multidimensional array and matrix data structures.
* 3. It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it. 
* 4. NumPy can be used to perform a wide variety of mathematical operations on arrays.


### How to install numpy?

* 1. conda install numpy
* 2. pip install numpy

### What’s the difference between a python list and a numpy array?*

* 1. NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them.

* 2. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous.

### Why use numpy not list?

* 1. Numpy arrays are faster and more compact than Python lists.
* 2. An array consumes less memory and is convenient to use. 

### What is array?

* 1. An array is a central data structure of the NumPy library.
* 2. The rank of the array is the number of dimensions. 
* 3. The shape of the array is a tuple of integers giving the size of the array along each dimension.

In [1]:
import numpy as np

a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [2]:
a.shape

(5,)

In [3]:
a.size

5

In [4]:
a.ndim

1

### Diffrent types of array

* 1D array
* 2D array
* 3D array

In [5]:
#1D array

array = np.array([11,12,13])
array

array([11, 12, 13])

In [6]:
array.ndim

1

In [7]:
#2D array

array = np.array([[11,12,13],[21,22,23]])
array

array([[11, 12, 13],
       [21, 22, 23]])

In [8]:
array.ndim

2

In [9]:
#3D array 

array = np.array([[[11,12,13],[21,22,23]],[[31,32,33],[41,42,43]]])
array

array([[[11, 12, 13],
        [21, 22, 23]],

       [[31, 32, 33],
        [41, 42, 43]]])

In [10]:
array.ndim

3

### Diffrent way to create arrays


In [11]:
#zeros

a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
#ones

a = np.ones((4,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
#empty

a = np.empty((3,4))
a

array([[1.06201113e-311, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.08221785e-312, 2.42336543e-057, 5.20940314e-090,
        4.27969695e-037],
       [1.26917811e-076, 3.11531493e+179, 3.99910963e+252,
        4.93432906e+257]])

In [14]:
#arrange

a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [15]:
#identity 

x = np.identity(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Indexing

In [16]:
#1D array

array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [17]:
#if we want to print 5 then...

print(array[4]) #indexing starting from 0 hence we got input 3...

5


In [18]:
#if we want to print 2 then...

print(array[1])

2


In [19]:
#2D array

arr = np.array([[11,12,13,14],[21,22,23,24]])
arr

array([[11, 12, 13, 14],
       [21, 22, 23, 24]])

In [20]:
#if we want to print 13 then...

print(arr[0,2])

13


In [21]:
#if we want to print 21 then...

print(arr[1,0])

21


In [22]:
#if we want to print 22 then...

print(arr[1,1])

22


In [23]:
#3D array

ar = np.array([[[11,12,13,14],[21,22,23,24]],[[31,32,33,34],[41,42,43,44]]])
ar

array([[[11, 12, 13, 14],
        [21, 22, 23, 24]],

       [[31, 32, 33, 34],
        [41, 42, 43, 44]]])

In [24]:
#if we want to print 42...

print(ar[1,1,1])

42


In [25]:
#if we want to print [42,43] then...

print(ar[1,1,1:3])

[42 43]


In [26]:
#if we want to print [22,23,24] then...

print(ar[0,1,1:4])

[22 23 24]


In [27]:
#if we want to print [31,32,33,34] then...

print(ar[1,0])

[31 32 33 34]


### Sorting, Adding & Spliting index

In [28]:
#Sorting index

a = np.array([4,2,3,1])
a.sort()
print(a)

[1 2 3 4]


In [29]:
b = np.array([[11,13,15,14],[24,21,33,45]])
b.sort()
print(b)

[[11 13 14 15]
 [21 24 33 45]]


In [30]:
arr = np.array(['banana', 'cherry', 'apple'])
arr.sort()
print(arr)

['apple' 'banana' 'cherry']


In [31]:
#Adding index

a1 = np.array([1,3,5,7])
a2 = np.array([5,7,9,11])


In [32]:
a3 = np.concatenate((a1, a2))
a3

array([ 1,  3,  5,  7,  5,  7,  9, 11])

In [33]:
b1 = np.array([[1,2,3],[4,5,6]])
b2 = np.array([[3,2,1],[6,5,4]])

b3 = np.concatenate((b1, b2))
b3

array([[1, 2, 3],
       [4, 5, 6],
       [3, 2, 1],
       [6, 5, 4]])

In [34]:
#Spliting index

x = np.array([1,2,3,4,5,6,7,8])

x1 = np.array_split(x, 4)
x1

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

### Reshape index

In [35]:
aa = np.arange(9)
aa

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
aa1 = aa.reshape(3,3)
aa1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### How to convert numpy array to pandas DataFrame

In [37]:
import pandas as pd

a = np.array([[11,12,13],[21,22,23]])

df = pd.DataFrame(a,columns=["A","B","C"])
df


A   B   C
0  11  12  13
1  21  22  23

### How to read csv in numpy

In [38]:
data = np.loadtxt(r"C:\Users\omkar.magar\Downloads\MOCK_DATA (3).csv",delimiter=',',dtype = str)
data

array([['name', 'usn', 'Att'],
       ['Cly', '38', '22'],
       ['Oberon', '90', '65'],
       ...,
       ['Giacopo', '100', '24'],
       ['Danny', '22', '71'],
       ['Walt', '85', '46']], dtype='<U11')

In [39]:
df = pd.DataFrame(data)
df.head(10)

0    1    2
0        name  usn  Att
1         Cly   38   22
2      Oberon   90   65
3   Cristobal  100   73
4        Dell   39   55
5  Franciskus   91  100
6   Leicester   98   77
7         Ruy   63   35
8      Tobiah   78    7
9    Carleton   82    8