### What is numpy?

* 1. Numpy (Numerical Python) is an open source python library.
* 2. The numpy library contains multidimensional array and matrix data structures.
* 3. It provides nd-array, a homogeneous n-dimensional array object, with methods to efficiently operate on it. 
* 4. Numpy can be used to perform a wide variety of mathematical operations on arrays.


### How to install numpy?

* 1. conda install numpy
* 2. pip install numpy

### What’s the difference between a python list and a numpy array?*

* 1. Numpy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them.

* 2. While a python list can contain different data types within a single list, all of the elements in a numpy array should be homogeneous.
* 3. List is an in-built data structure, whereas, for an array, we need to import it from the array or numpy package.

### Why use numpy not list?

* 1. Numpy arrays are faster and more compact than python lists.
* 2. An array consumes less memory and is convenient to use. 

In [1]:
import numpy as np

a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [2]:
a.shape

(5,)

In [3]:
a.size

5

In [4]:
a.ndim

1

### Diffrent types of array

* 1D array
* 2D array
* 3D array

In [5]:
#1D array

array = np.array([11,12,13])
array

array([11, 12, 13])

In [6]:
array.ndim

1

In [7]:
#2D array

array = np.array([[11,12,13],[21,22,23]])
array

array([[11, 12, 13],
       [21, 22, 23]])

In [8]:
array.ndim

2

In [9]:
#3D array 

array = np.array([[[11,12,13],[21,22,23]],[[31,32,33],[41,42,43]]])
array

array([[[11, 12, 13],
        [21, 22, 23]],

       [[31, 32, 33],
        [41, 42, 43]]])

In [10]:
array.ndim

3

### Diffrent way to create arrays


In [11]:
#zeros

a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
#ones

a = np.ones((4,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
#empty

a = np.empty((3,4))
a

array([[1.01690074e-311, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.12465777e-312, 6.82116729e-043, 6.56446035e-091,
        5.64053561e-062],
       [8.31989567e-072, 3.34868728e-061, 3.99910963e+252,
        1.82960278e+184]])

In [14]:
#arrange

a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [15]:
#identity 

x = np.identity(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
#fill

z = np.empty((3,4))
z.fill(3)
z

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

### Indexing

In [17]:
#1D array

array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [18]:
#if we want to print 5 then...

print(array[4]) #indexing starting from 0 hence we got input 3...

5


In [19]:
#if we want to print 2 then...

print(array[1])

2


In [20]:
#2D array

arr = np.array([[11,12,13,14],[21,22,23,24]])
arr

array([[11, 12, 13, 14],
       [21, 22, 23, 24]])

In [21]:
#if we want to print 13 then...

print(arr[0,2])

13


In [22]:
#if we want to print 21 then...

print(arr[1,0])

21


In [23]:
#if we want to print 22 then...

print(arr[1,1])

22


In [24]:
#3D array

ar = np.array([[[11,12,13,14],[21,22,23,24]],[[31,32,33,34],[41,42,43,44]]])
ar

array([[[11, 12, 13, 14],
        [21, 22, 23, 24]],

       [[31, 32, 33, 34],
        [41, 42, 43, 44]]])

In [25]:
#if we want to print 42...

print(ar[1,1,1])

42


### Slicing of index 

In [26]:
#if we want to print [42,43] then...

print(ar[1,1,1:3])

[42 43]


In [27]:
#if we want to print [22,23,24] then...

print(ar[0,1,1:4])

[22 23 24]


In [28]:
#if we want to print [31,32,33,34] then...

print(ar[1,0])

[31 32 33 34]


In [29]:
#1D array

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5]) #(start:end)

[2 3 4 5]


In [30]:
arr1 = np.array([11,12,13,14,15])

print(arr1[2:5])

[13 14 15]


In [31]:
#2D array

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [32]:
arr1 = np.array([[11,12,13,],[21,22,23]])

print(arr1[0,0:2])

[11 12]


### Sorting, Adding & Spliting index

In [33]:
#Sorting index

a = np.array([4,2,3,1])
a.sort()
print(a)

[1 2 3 4]


In [34]:
b = np.array([[11,13,15,14],[24,21,33,45]])
b.sort()
print(b)

[[11 13 14 15]
 [21 24 33 45]]


In [35]:
arr = np.array(['banana', 'cherry', 'apple'])
arr.sort()
print(arr)

['apple' 'banana' 'cherry']


In [36]:
#Adding index

a1 = np.array([1,3,5,7])
a2 = np.array([5,7,9,11])


In [37]:
a3 = np.concatenate((a1, a2))
a3

array([ 1,  3,  5,  7,  5,  7,  9, 11])

In [38]:
b1 = np.array([[1,2,3],[4,5,6]])
b2 = np.array([[3,2,1],[6,5,4]])

b3 = np.concatenate((b1, b2))
b3

array([[1, 2, 3],
       [4, 5, 6],
       [3, 2, 1],
       [6, 5, 4]])

In [39]:
#Spliting index

x = np.array([1,2,3,4,5,6,7,8])

x1 = np.array_split(x, 4)
x1

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

### Reshape index

In [40]:
aa = np.arange(9)
aa

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
aa1 = aa.reshape(3,3)
aa1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### Numpy Copy and View

In [42]:
arr = np.array([1, 2, 3, 4, 5]) #Copy function used to replce value by index without replacing orignal...
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [45]:
arr1 = np.array([1, 2, 3, 4, 5])#View function used to replce value by index with replacing orignal...
x = arr1.view()
arr1[0] = 42

print(arr1)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [46]:
arr2 = np.array([11,22,13,44,55])
x = arr2.copy()
arr2[2] = 33
print(arr2)
print(x)

[11 22 33 44 55]
[11 22 13 44 55]


In [47]:
arr3 = np.array([11,22,13,44,55])
x = arr3.view()
arr3[2] = 33
print(arr3)
print(x)

[11 22 33 44 55]
[11 22 33 44 55]


### Numpy searching array

In [49]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [50]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0) #odd number

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [51]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1) #even number

print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [54]:
import random 
a = np.random.randint(100,size=(100))
a_re = a.reshape(20,5)
a_re

array([[64, 44, 85, 34, 41],
       [31, 56, 45, 64, 95],
       [45, 20, 64, 42, 74],
       [81, 15, 43, 82, 87],
       [77, 75, 95, 43, 91],
       [92, 52, 37, 87, 87],
       [30, 87, 74, 64, 13],
       [36, 78, 56, 86, 68],
       [24, 42, 96, 90, 29],
       [16, 64, 80, 11, 12],
       [62, 41, 85, 48, 42],
       [85, 20, 56, 34, 63],
       [40, 51, 16, 97, 52],
       [83, 88, 81, 12, 48],
       [ 4, 26, 28, 13, 92],
       [59, 68, 19, 28, 11],
       [89, 58, 19, 86, 88],
       [85, 62, 41,  8, 33],
       [63, 13,  7, 29, 76],
       [12, 10, 30,  2,  3]])

In [55]:
my_df = pd.DataFrame(a_re,columns=["A","B","C","D","E"])
my_df

A   B   C   D   E
0   64  44  85  34  41
1   31  56  45  64  95
2   45  20  64  42  74
3   81  15  43  82  87
4   77  75  95  43  91
5   92  52  37  87  87
6   30  87  74  64  13
7   36  78  56  86  68
8   24  42  96  90  29
9   16  64  80  11  12
10  62  41  85  48  42
11  85  20  56  34  63
12  40  51  16  97  52
13  83  88  81  12  48
14   4  26  28  13  92
15  59  68  19  28  11
16  89  58  19  86  88
17  85  62  41   8  33
18  63  13   7  29  76
19  12  10  30   2   3

In [56]:
my_df.sample(frac=1,axis=1) #sample is used to reshuffle data in dataframe...

B   D   C   E   A
0   44  34  85  41  64
1   56  64  45  95  31
2   20  42  64  74  45
3   15  82  43  87  81
4   75  43  95  91  77
5   52  87  37  87  92
6   87  64  74  13  30
7   78  86  56  68  36
8   42  90  96  29  24
9   64  11  80  12  16
10  41  48  85  42  62
11  20  34  56  63  85
12  51  97  16  52  40
13  88  12  81  48  83
14  26  13  28  92   4
15  68  28  19  11  59
16  58  86  19  88  89
17  62   8  41  33  85
18  13  29   7  76  63
19  10   2  30   3  12

In [57]:
my_df.sample(frac=1,axis=0)

A   B   C   D   E
4   77  75  95  43  91
18  63  13   7  29  76
17  85  62  41   8  33
11  85  20  56  34  63
13  83  88  81  12  48
15  59  68  19  28  11
14   4  26  28  13  92
19  12  10  30   2   3
0   64  44  85  34  41
5   92  52  37  87  87
3   81  15  43  82  87
7   36  78  56  86  68
16  89  58  19  86  88
8   24  42  96  90  29
1   31  56  45  64  95
10  62  41  85  48  42
6   30  87  74  64  13
9   16  64  80  11  12
2   45  20  64  42  74
12  40  51  16  97  52

In [58]:
my_df.sample(frac=0.5,axis=1)

D   E
0   34  41
1   64  95
2   42  74
3   82  87
4   43  91
5   87  87
6   64  13
7   86  68
8   90  29
9   11  12
10  48  42
11  34  63
12  97  52
13  12  48
14  13  92
15  28  11
16  86  88
17   8  33
18  29  76
19   2   3

In [59]:
my_df.sample(frac=0.5,axis=0)

A   B   C   D   E
2   45  20  64  42  74
11  85  20  56  34  63
18  63  13   7  29  76
17  85  62  41   8  33
8   24  42  96  90  29
1   31  56  45  64  95
10  62  41  85  48  42
9   16  64  80  11  12
19  12  10  30   2   3
6   30  87  74  64  13

In [60]:
output = np.ones((5,5),dtype=int)
zeros = np.zeros((3,3))
output[1:4,1:4] = zeros
output[2:3,2]= 9
output

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

### How to convert numpy array to pandas DataFrame

In [69]:
import pandas as pd

a = np.array([[11,12,13],[21,22,23]])

df = pd.DataFrame(a,columns=["A","B","C"])
df

A   B   C
0  11  12  13
1  21  22  23

### How to read csv in numpy

In [70]:
data = np.loadtxt(r"C:\Users\Gayu Magar\Downloads\Mall_Customers.csv",delimiter=',',dtype = str)
data

array([['CustomerID', 'Gender', 'Age', 'Annual Income (k$)',
        'Spending Score (1-100)'],
       ['1', 'Male', '19', '15', '39'],
       ['2', 'Male', '21', '15', '81'],
       ...,
       ['198', 'Male', '32', '126', '74'],
       ['199', 'Male', '32', '137', '18'],
       ['200', 'Male', '30', '137', '83']], dtype='<U22')

In [71]:
df = pd.DataFrame(data)
df.head(10)

0       1    2                   3                       4
0  CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
1           1    Male   19                  15                      39
2           2    Male   21                  15                      81
3           3  Female   20                  16                       6
4           4  Female   23                  16                      77
5           5  Female   31                  17                      40
6           6  Female   22                  17                      76
7           7  Female   35                  18                       6
8           8  Female   23                  18                      94
9           9    Male   64                  19                       3